title: Juyoung Wang
logo: /assets/img/logo.png
layout: splash
description: This is Juyoung Wang's personal website.
show_downloads: false
google_analytics: G-0LS82TNLJ6
theme: jekyll-theme-minimal
kramdown:
  math_engine: mathjax