title: Juyoung Wang
logo: /assets/img/logo.png
description: This is Juyoung Wang's personal website :) It's my first time using gh-page. Enjoy!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
